version: "3"

networks:
  nocobase:
    driver: bridge

services:
  app:
    image: nocobase/nocobase:latest
    networks:
      - nocobase
    depends_on:
      - postgres
    environment:
      # The application's secret key, used to generate user tokens, etc.
      # If APP_KEY is changed, old tokens will also become invalid.
      # It can be any random string, and make sure it is not exposed.
      - APP_KEY=your-secret-key
      # Database type, supports postgres, mysql, mariadb
      - DB_DIALECT=postgres
      # Database host, can be replaced with the IP of an existing database server
      - DB_HOST=postgres
      # Database name
      - DB_DATABASE=nocobase
      # Database user
      - DB_USER=nocobase
      # Database password
      - DB_PASSWORD=nocobase
      # Whether to convert table and field names to snake_case
      - DB_UNDERSCORED=true
    volumes:
      # Mount the storage directory for uploading files
      - ./storage:/app/nocobase/storage
    ports:
      # Map port 13000 in the container to port 12000 on the host
      - "12000:13000"
    # Run the app in the foreground
    command: [sh, -c, "yarn start"]

  # If using an existing database server, you can comment out the postgres service below
  postgres:
    image: postgres:16
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: nocobase
      POSTGRES_DB: nocobase
      POSTGRES_PASSWORD: nocobase
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    networks:
      - nocobase